delivery/urls.py
from django.urls import path , include
from . import views
from rest_framework import routers

app_name = 'delivery'

router = routers.SimpleRouter()

urlpatterns = [
    path('orders/', views.orders , name='deliveries'),
    path('drivers/', views.drivers , name='drivers'),
    path('trips/', views.trips , name='trips'),
    path('driverTrips/<str:id>/', views.driver_trips , name='driver_trips'),
    path('driverTrips/<str:id>/<str:trip_id>/', views.driver_ind_trip , name='driver_ind_trip'),
]

router.register(r'order', views.OrderViewSet , basename = 'order')
router.register(r'driver', views.DriverViewSet, basename = 'driver')
router.register(r'trip', views.TripViewSet, basename = 'trip')


urlpatterns += router.urls

synos/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('excel/', include('excelImport.urls')),
    path('core/', include('delivery.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('account/',include('account.urls')), 
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

delivery/forms.py
from django import forms
from .models import Order , Driver
from django.forms import BoundField


class FieldSet(object):
    def __init__(self,form,fields,id,legend='',cls=None):
        self.form = form
        self.id = id
        self.legend = legend
        self.fields = fields
        self.cls = cls

    def __iter__(self):
        for name in self.fields:
            field = self.form.fields[name]
            yield BoundField(self.form, field, name)



class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ["latitude",'longitude','status']
        widgets = {'address': forms.TextInput(attrs={
            'class': 'form-control',
            'autoComplete': True,
            }),
            'time_from':forms.TextInput(attrs={
            'type': 'datetime-local',
            'value':''
            }),
            'time_to':forms.TextInput(attrs={
            'type': 'datetime-local',
            }),
        }

class DriverForm(forms.ModelForm):
    class Meta:
        model =Driver
        exclude = ["latitude",'longitude']
        widgets = {'address': forms.TextInput(attrs={
            'class': 'form-control',
            'autoComplete': True,
            }),
        }

delivery/views.py
from rest_framework import viewsets
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework import serializers

from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.core.mail import EmailMultiAlternatives
from django.urls import reverse
from django.utils import timezone

from datetime import timedelta

from .models import Order,Driver,Trip
from .serializer import OrderSerializer , DriverSerializer, TripSerializer
from .forms import OrderForm,FieldSet,DriverForm
from utils.requests import dispatching_request,disposition_request
from utils.helper import geocoder
from .filters import OrderFilter , TripFilter

@login_required
def orders(request):
    form = OrderForm()
    fieldsets = (FieldSet(form,('address',),'address',
                        legend='Recipient details',),
                FieldSet(form, ('time_from','time_to'),'time', 
                            legend="Delivery time window"),
                FieldSet(form, ('height','width','depth'),'dimensions', 
                            legend="Delivery dimensions"),
                FieldSet(form, ('buffer','order_type','weight'),'other',
                            legend="Other detials"),
                )
    return render(request, 'delivery/deliveries.html',{'form':form,'fieldsets':fieldsets,'deliveries':True})

@login_required
def drivers(request):
    form = DriverForm()
    fieldsets = (FieldSet(form,('address','email','name'),'address',
                        legend='Driver details',),
                FieldSet(form, ('height','width','depth'),'dimensions', 
                            legend="Vehicle dimensions"),
                FieldSet(form, ('max_weight',),'other',
                            legend="Other detials"),
        )
    return render(request, 'delivery/drivers.html',{'drivers':True,'form':form,'fieldsets':fieldsets})


@login_required
def trips(request):
    return render(request, 'delivery/trips.html',{'trips':True})



def driver_trips(request,id):
    trips = []
    
    for t in Trip.objects.filter(driver__id=id):
        if t.status != 3:
            trips.append(t)

    return render(request, 'delivery/driver_trips.html',{'trips':trips,'id':id})

def driver_ind_trip(request,id,trip_id):
    trip = Trip.objects.get(driver__id=id,id=trip_id)
    if request.method == 'POST':
        order = Order.objects.get(id = request.POST.get('id'))
        order.status = int(request.POST['status'])
        order.save()
        return JsonResponse(OrderSerializer(order).data)
    return render(request, 'delivery/driver_ind_trip.html',{'trip':trip,'id':id,'trip_id':trip_id})

class OrderViewSet(viewsets.ModelViewSet):
    serializer_class = OrderSerializer
    filterset_class = OrderFilter
    ordering_fields = "__all__"
    search_fields = ['id','address','trip__driver__name']

    def get_queryset(self):
        return Order.objects.filter(user = self.request.user).order_by('status')

    def perform_create(self, serializer):
        geocode = geocoder(serializer.validated_data['address'])
        if geocode:
            lat = geocode.latitude
            lon = geocode.longitude
            serializer.save(user=self.request.user,latitude = lat, longitude = lon)
        else:
            raise serializers.ValidationError({'address':'Address could not be geocoded'})
    
    def perform_update(self, serializer):
        id = self.request.parser_context['kwargs']['pk']
        order = Order.objects.get(id=id)
        if (self.request.method == "PATCH" and serializer.validated_data.get('address',None)) or self.request.method == "PUT":
            if order.address != serializer.validated_data['address']:
                geocode = geocoder(serializer.validated_data['address'])
                if geocode:
                    lat = geocode.latitude
                    lon = geocode.longitude
                    serializer.save(latitude = lat, longitude = lon)
                else:
                    raise serializers.ValidationError({'address':'Address could not be geocoded'})
            else:
                serializer.save()
        else:
            serializer.save()

    @action(detail=False,methods=['post'])
    def bulk_delete(self, *args, **kwargs):
        ids = self.request.data.get('ids',[])
        self.get_queryset().filter(id__in=ids).delete()
        return Response({'delete': True})

    @action(detail=False,methods=['post'])
    def bulk_update(self, *args, **kwargs):
        ids = self.request.data.get('id',[])
        queryset = self.get_queryset().filter(id__in=ids)
        queryset.update(**self.request.data.get('data',{}))
        serializer = self.serializer_class(queryset, many=True)
        return Response(serializer.data)

    @action(detail=True,methods=['post'])
    def remove_trip(self, request, pk=None):
        order = Order.objects.get(id=pk)
        trip = Trip.objects.get(id=order.trip.id)
        order.trip = None
        order.save()
        trip.recalculate()
        serializer = self.serializer_class(order)
        return Response(serializer.data)

class DriverViewSet(viewsets.ModelViewSet):
    serializer_class = DriverSerializer
    filterset_fields = "__all__"
    ordering_fields = "__all__"

    def get_queryset(self):
        return Driver.objects.filter(user = self.request.user).order_by('id')

    @action(detail=False,methods=['post'])
    def bulk_delete(self, *args, **kwargs):
        ids = self.request.data.get('ids',[])
        self.get_queryset().filter(id__in=ids).delete()
        return Response({'delete': True})

    def perform_create(self, serializer):
        geocode = geocoder(serializer.validated_data['address'])
        if geocode:
            lat = geocode.latitude
            lon = geocode.longitude
            serializer.save(user=self.request.user,latitude = lat, longitude = lon)
        else:
            raise serializers.ValidationError({'address':'Address could not be geocoded'})
    
    def perform_update(self, serializer):
        id = self.request.parser_context['kwargs']['pk']
        driver = Driver.objects.get(user = self.request.user,id=id)
        if (self.request.method == "PATCH" and serializer.validated_data.get('address',None)) or self.request.method == "PUT":
            if driver.address != serializer.validated_data['address']:
                geocode = geocoder(serializer.validated_data['address'])
                if geocode:
                    lat = geocode.latitude
                    lon = geocode.longitude
                    serializer.save(latitude = lat, longitude = lon)
                else:
                    raise serializers.ValidationError({'address':'Address could not be geocoded'})
            else:
                serializer.save()
        else:
            serializer.save()

    @action(detail=True,methods=['post'])
    def send_mail(self, request, pk=None):
        driver = self.get_object()
        driver.notify("Your web app Link" , '')
        return Response({"sent":True})




class TripViewSet(viewsets.ModelViewSet):
    serializer_class = TripSerializer
    filterset_class = TripFilter
    ordering_fields = "__all__"

    def get_queryset(self):
        return Trip.objects.filter(user = self.request.user)


    @action(detail=True,methods=['post'])
    def driver_update(self, *args, **kwargs):
        driver = self.request.data.get("driver",None)
        self.get_queryset().filter(**kwargs).update(driver = Driver.objects.get(id=driver))
        return Response({'update': True})

    @action(detail=False,methods=['post'])
    def bulk_order_update(self, *args, **kwargs):
        id = self.request.data.get('id')
        queryset = self.get_queryset().get(id=id)
        queryset.order_set.all().update(**self.request.data.get('data',{}))
        serializer = self.serializer_class(queryset)
        return Response(serializer.data)

    def create(self, request):
        orderIDs = request.data.get("orderIDs",[])
        driverIDs = request.data.get("driverIDs",[])
        indexes = request.data.get("indexes",{'distance_index':0.4 , 'duration_index':0.4 , 'worth_index':0.2})
        constraints =request.data.get("constraints",{'max_orders_per_driver':50 , 'start_time':timezone.now()})
        worth = request.data.get("worth",'buffer')
        orders = Order.objects.filter(id__in = [o for o in orderIDs],status = 0)
        drivers = Driver.objects.filter(id__in = [d for d in driverIDs])
        result = dispatching_request(orders , drivers , constraints , indexes,worth)
        trips = result['trips']
        res = []
        for t  in trips:
            driver = Driver.objects.get(id=t['driver']['identification'])
            trip = Trip.objects.create(user=self.request.user,total_duration = t['total_duration'] , total_distance = t['total_distance'] , start_time = t['start_time']
             , end_time = t['end_time'], polyline = t['polyline'],driver = driver , start_address = driver.address ,  start_latitude = driver.latitude , start_longitude = driver.longitude,worth = worth,
             distance_index = indexes['distance_index'] , duration_index = indexes['duration_index'] , worth_index = indexes['worth_index'])
            res.append(trip)
            for o in t['orders']:
                order = Order.objects.get(id=o['identification'])
                order.trip = trip
                order.start_time = o['start_time']
                order.end_time = o['end_time']
                order.arrival_time   = o['arrival_time']
                order.stop_id = o['stop_id']
                order.status = 1
                order.duration = o['duration']
                order.distance = o['distance']
                order.save()   

        return Response({'data':self.serializer_class(res,many=True).data,"unassigned":len(result['unassigned_orders'])},status=201)  

templates/delivery/base.html
{% extends 'bases/base.html' %}
{% load static %}
{% block title %} {% endblock %}

{% block stylesheets %}
<link href="https://unpkg.com/tabulator-tables/dist/css/tabulator.min.css" rel="stylesheet">
<link href="{% static 'tabulator.min.css' %}" rel="stylesheet">
<link href="{% static 'custom-tabulator.css' %}" rel="stylesheet">
{% block baseStylesheets %}
{% endblock %}

{% endblock %}

{% block scripts %}
<script type="text/javascript" src="https://unpkg.com/tabulator-tables/dist/js/tabulator.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/moment@2.29.3/moment.min.js"></script>
<script
    src="https://maps.googleapis.com/maps/api/js?key={{googleApiKey}}&libraries=places">
</script>
{% block basescripts %}
{% endblock %}

{% endblock %}


{% block css %}
<style>
    .search{
        max-width: 280px;
    }
</style>
{% block basecss %}
{% endblock %}

{% endblock %}

{% block body %}

{% block baseBody %}
{% endblock %}

{% endblock %}


{% block js %}
<script>
$.ajaxSetup({
        headers: {
            'Authorization': 'Token {{userToken}}',
        }
});
</script>
    
    {% block basejs %}
    {% endblock %}
{% endblock %}

templates/delivery/driver_app_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Drivers App</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'base.css'%}">
    {% block stylesheet %}
    {% endblock %}
</head>

<style>
    
</style>
{% block css %}
{% endblock %}
<body>
    <div class="container-fluid d-flex justify-content-start align-items-center h-50p border-bottom">
        <div class="d-flex me-auto" style="width: 200px;">
            <img src="https://synertics.io/staticfiles/img/logo-vector.svg" alt="synertics_logo" class="logo">
        </div>
    </div>
    <div class="container mt-3 " style="position:relative">
        {% block body %}
        {% endblock %}
    </div>
</body>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/f690328fff.js" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/notiflix@3.2.5/dist/notiflix-aio-3.2.5.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/moment@2.29.3/moment.min.js"></script>

{% block scripts %}
{% endblock %}

<script>
    Notiflix.Confirm.init({
        titleColor: '#126caa',
        okButtonColor: '#fff',
        okButtonBackground: '#126caa',
        borderRadius:"5px"
    })

    Notiflix.Notify.init({
        borderRadius:"5px",
        position:"left-bottom"
    })

    Notiflix.Loading.init({
        backgroundColor:"#ffffff50",
        svgColor:"#126caa"
    })

    Notiflix.Block.init({
        svgColor:"#126caa"
    })


    Notiflix.Loading.pulse();
    $(document).ready(function(){
        Notiflix.Loading.remove();

    });
</script>
{% block js %}
{% endblock %}
</html>

templates/delivery/driver_ind_trip.html
{% extends 'delivery/driver_app_base.html' %}
{% load static %}
{% block stylesheet %}
<link href='https://api.mapbox.com/mapbox-gl-js/v2.0.1/mapbox-gl.css' rel='stylesheet' />

{% endblock %}

{% block css %}
<style>
    .trip-div{
        border-radius: 10px;
        background-color: #fff;
        padding: 10px;
        margin-bottom: 10px;
        width:100%;
        max-width: 350px;
        cursor: pointer;
    }
    p{
        color: rgb(34, 34, 34);
        font-size: 14px;
    }
    #mapid{
        width: 100%;
        height: 310px;
    }
</style>
{% endblock %}

{% block body %}
<a href="{% url 'delivery:driver_trips' id=id %}" class="text-syn h4" style="    position: absolute;
right: 80px;"><i class="fas fa-arrow-alt-circle-left"></i></a>
<h4 class="text-syn text-center">
    Orders
</h4>
<div id="mapid" width="100%" height="100%">

</div>
<div class="d-flex flex-column w-100 justify-content-start align-items-center py-2" style="max-height: calc(100vh - 110px);overflow-y: auto;">
    {% if trip %}
    {% for order in trip.order_set.all %}
    <div class="d-flex flex-wrap trip-div justify-content-between align-items-start shadow border" id="{{order.id}}">
        <div>
            <p class="m-0 mb-1 text-grey"> Address </p>
            <p class="m-0 mb-1"> {{order.address}} </p>
        </div>
        {% if order.status == 3 %}
        <div class="d-flex w-100 justify-content-center mt-3">
            <button class="btn btn-success"> Completed </button>
        </div>
        {% else %}
        <div class="d-flex w-100 justify-content-between mt-3">
        <button class="btn btn-success" onclick="change_status(3,'{{order.id}}')"> Complete </button>
        <button class="btn btn-danger" onclick="change_status(0,'{{order.id}}')"> Cancel </button>
        <a class="btn btn-primary" href="http://maps.google.com/maps?saddr={{trip.start_latitude}},{{trip.start_longitude}}&daddr={{order.latitude}},{{order.longitude}}" target="_blank"> Map </a>
        </div>
        {% endif %}
    </div>
    {% endfor %}
    {% else %}
    {% endif %}
</div>
{% endblock %}


{% block scripts %}
<script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"integrity="sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew=="crossorigin=""></script>
<script src='https://api.mapbox.com/mapbox-gl-js/v2.0.1/mapbox-gl.js'></script>
<script src="{% static 'js/flexiblePolyline.js' %}"></script>

{% endblock %}

{% block js %}

<script>

    mapboxgl.accessToken = '{{mapboxApiKey}}'

    var map = new mapboxgl.Map({
        container: 'mapid',
        style: 'mapbox://styles/mapbox/streets-v11',//'mapbox://styles/mapbox/streets-v11',//'mapbox://styles/cosmoboiy/ckug8xffi8jnq17prcevd5q9o',
        center: [8.699088662141811,50.301355799999996],
        zoom: 8
    });

    map.on('load',()=>{
        get_layers()
    })

    const get_layers = (trip)=>{
        orders_geojson = {
            "type": "FeatureCollection",
            "features": []
        }

        routes_geojson = {
            "type": "FeatureCollection",
            "features": []
        }

        driver_geojson = {
            "type": "FeatureCollection",
            "features": []
        }
        {% for order in trip.order_set.all %}
            orderData = {
                "type": "Feature",
                "properties": {number:'{{order.stop_id}}'},
                "geometry": {
                    "type": "Point",
                    "coordinates": [parseFloat("{{order.longitude}}"),parseFloat("{{order.latitude}}")]
                }
            }   
            orders_geojson.features.push(orderData)
        {% endfor %}
        polyline = decode('{{trip.polyline}}')        
        let routeData = {
                "type": "Feature",
                "properties": {},
                "geometry": {
                    "type": "LineString",
                    "coordinates": polyline.polyline
                }
        }
        routes_geojson.features.push(routeData)
        
        let driverData = {
            "type": "Feature",
                "properties": {},
                "geometry": {
                    "type": "Point",
                    "coordinates": [parseFloat("{{trip.start_longitude}}"),parseFloat("{{trip.start_latitude}}")]
                }
        }

        driver_latlon = [parseFloat("{{trip.start_longitude}}"),parseFloat("{{trip.start_latitude}}")]

        driver_geojson.features.push(driverData)

        add_routes_layer(routes_geojson)
        add_orders_layer(orders_geojson)
        add_drivers_layer(driver_geojson)
    }

    const add_orders_layer = (data)=>{
        map.addSource('ordersSource', {
        'type': 'geojson',
        'data':data
        });

        if (!map.hasImage("order_img")){
            let url = 'https://api.tiles.mapbox.com/v3/marker/pin-s+126caa.png';
            map.loadImage(url, function(err, image) {
            if (err) {
            console.error('err image', err);
            return;
            }
            map.addImage('order_img', image);
            map.addLayer({
                'id': 'orders',
                'type': 'symbol',
                'source': 'ordersSource',
                'layout': {
                    'icon-allow-overlap': true,
                    'text-allow-overlap':true,
                    'icon-image': 'order_img',
                    // get the title name from the source's "title" property
                    'text-field': ['get', 'number',],
                    'text-font': [
                    'Open Sans Semibold',
                    'Arial Unicode MS Bold'
                    ],
                    'text-size': 11,
                    'text-offset': [0, 0.25],
                    'text-anchor': 'top'
                    }
            });
        })

        
        }
    }

    const add_drivers_layer = (data)=>{
        map.addSource('driversSource', {
        'type': 'geojson',
        'data':data
        });
        if (!map.hasImage("driver_img")){
            let url = '{% static "img/Ellipse.png" %}';
            map.loadImage(url, function(err, image) {
            if (err) {
            console.error('err image', err);
            return;
            }
            map.addImage('driver_img', image);
            map.addLayer({
                'id': 'drivers',
                'type': 'symbol',
                'source': 'driversSource',
                'layout': {
                    'icon-allow-overlap': true,
                    'text-allow-overlap':true,
                    'icon-image': 'driver_img',
                    }
                });
            })  
        }
        map.flyTo({
            center: driver_latlon
        });
    }

    const add_routes_layer = (data)=>{
        map.addSource('routesSource', {
            'type': 'geojson',
            'data':data
        });

        map.addLayer({
            'id': 'routes',
            'type': 'line',
            'source': 'routesSource',
            'layout': {
                'line-join': 'round',
                'line-cap': 'round'
            },
            'paint': {
                'line-color': '#126caa',
                // '#888',
                'line-width': 5
            }
        });
    }


    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    var csrftoken = getCookie('csrftoken');

    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });
    change_status = (status,id) => {
        $.ajax({
            url:"{% url 'delivery:driver_ind_trip' id=id trip_id=trip_id %}",
            method:"POST",
            data:{
                status:status,
                id:id
            },
            success:function(data){
                el = document.getElementById(`${id}`)
                if (status == 0){
                    el.remove()
                }
                else if(status == 3){
                    el.innerHTML = `
                    <div>
                        <p class="m-0 mb-1 text-grey"> Address </p>
                        <p class="m-0 mb-1"> ${data.address} </p>
                    </div>
                    <div class="d-flex w-100 justify-content-center mt-3">
                        <button class="btn btn-success"> Completed </button>
                    </div>
                    `
                }
            },
            error:function(data){
                console.log(data);
            }
        })
    }
</script>

{% endblock %}

templates/delivery/driver_trips.html
{% extends 'delivery/driver_app_base.html' %}
{% block stylesheet %}
{% endblock %}

{% block css %}
<style>
    .trip-div{
        border-radius: 10px;
        background-color: #fff;
        padding: 10px;
        margin-bottom: 10px;
        width:100%;
        max-width: 350px;
        cursor: pointer;
    }
    p{
        color: rgb(34, 34, 34);
        font-size: 14px;
    }
</style>
{% endblock %}

{% block body %}

<h4 class="text-syn text-center">
    Trips
</h4>
<div class="d-flex flex-column w-100 justify-content-start align-items-center py-2" style="max-height: calc(100vh - 110px);overflow-y: auto;">
    
    {% if trips %}
    {% for trip in trips %}
    <div class="d-flex trip-div justify-content-between align-items-start shadow border" data-id="{{trip.id}}">
        <div>
            <p class="m-0 mb-1 text-grey"> start Time </p>
            <p class="m-0 mb-1 time"> {{trip.start_time}} </p>
        </div>
        <div>
            <p class="m-0 mb-1 text-grey"> total deliveries </p>
            <p class="m-0 mb-1"> {{ trip.order_set.all|length }} </p>
        </div>
        <div class="d-flex flex-column">
            <p class="m-0 mb-1"> {% widthratio trip.total_duration 60 1 %}<span class="text-grey"> min.</span> </p>
            <p class="m-0 mb-1"> {% widthratio trip.total_distance 1000 1 %} <span class="text-grey">Km</span>  </p>
        </div>
    </div>
    {% endfor %}
    {% else %}
    <div class="d-flex flex-column trip-div justify-content-center align-items-center text-center" data-id="{{trip.id}}">
        <h4 class='text-center text-syn text-center'>
            <span class="fa-stack fa-2x">
                <i class="fas fa-map-marker-alt fa-stack-1x"></i>
                <i class="fas fa-ban fa-stack-2x"></i>
            </span>
        </h4>
        <h5 class='text-center text-syn'>No trips at the moment</h5>
    </div>
    {% endif %}
</div>


{% endblock %}


{% block scripts %}
{% endblock %}

{% block js %}

<script>
    $(document).ready(function(){
        $(".trip-div").click(function(){
            var trip_id = $(this).attr("data-id");
            window.location.href = "/core/driverTrips/{{id}}/"+trip_id;
        });
        

        document.querySelectorAll('.time').forEach((e)=>{
            e.innerHTML = moment.unix(parseFloat(e.innerHTML)).format('MMMM Do YYYY');
        });
    
    });

    
</script>

{% endblock %}