excelImport/urls.py
from django.urls import path , include
from . import views as vw

app_name = "excel"

urlpatterns = [
    path("import/",vw.importExcel , name="import"),
    path("fieldMapping/",vw.fieldMapping , name="fieldMapping"),
    path("addOrders/",vw.addDeliveries , name="addDeliveries"),
    path("update/",vw.correctData , name="update"),
    path("downloadExample/",vw.download_example , name="download_example"),
]

synos/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('excel/', include('excelImport.urls')),
    path('core/', include('delivery.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('account/',include('account.urls')), 
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

excelImport/models.py
from django.db import models

class ExcelFile(models.Model):
    file = models.FileField(upload_to='excel/')
    created = models.DateTimeField(auto_now_add=True)

    def delete(self, using=None, keep_parents=False):
        self.file.storage.delete(self.file.name)
        super().delete()

excelImport/views.py
import time
from django.http import JsonResponse
from django.shortcuts import render , redirect
from django.urls import reverse
from django.http import HttpResponse, Http404
from django.conf import settings

from .models import ExcelFile
from utils.helper import read_file , timeCorrection , positiveValue,geocoder , NanoID
from delivery.models import Order
from .helper import cleanFolder , orderTypeCheck , orderTypeconverter

import pandas as pd
import numpy as np
import dateutil.parser as parser
import json
import datetime
import os
import pytz



def importExcel(request):
    if request.method == 'POST':
        file = request.FILES['file']
        file = ExcelFile.objects.create(file=file)
        err , df = read_file(file)
        if err:
            return JsonResponse({'success':False},status=500)        
        request.session['fileId'] = file.id      
        return JsonResponse({'success':True},status=200)
    return render(request, 'excelImport/importExcel.html')




def fieldMapping(request,*args,**kwargs):
    if request.method == 'POST':
        geocoded = bool(request.POST.get('geocoded',None))
        data = dict( (v,k) for k , v in request.POST.items())
        file = ExcelFile.objects.get(id= request.session['fileId'])
        err , df = read_file(file)
        if not geocoded:
            df['gcode'] = df[data['address']].apply(geocoder)
            df['lat'] = [g.latitude if g != None else 0 for g in df.gcode]
            df['long'] = [g.longitude if g != None else 0 for g in df.gcode]
            data['lat'] = 'lat'
            data['lon'] = 'long'
        df['error'] = None
        orders = []
        for ID , order in df.iterrows():
            order['error'] = {}
            if order[data.get('lat','lat')] == 0:
                order['error']['address'] = 'Address could not be geocoded'

            timeFrom = str(order.get(data.get('timeFrom',None),None))
            timeTo = str(order.get(data.get('timeTo',None),None))

            if not pd.isnull(timeFrom) and timeFrom != 'NaT' and timeFrom != '':
                timeFrom , order['error'] = timeCorrection(timeFrom , order['error'] , 'timeFrom')
            else:
                timeFrom = ''
            if not pd.isnull(timeTo) and timeTo != 'NaT' and timeTo != '':
                timeTo , order['error'] = timeCorrection(timeTo,order['error'], 'timeTo')
            else:
                timeTo = ''

            weight , order['error'] = positiveValue(order.get(data.get('weight',None),None),order['error'],'weight')
            height , order['error'] = positiveValue(order.get(data.get('height',None),None),order['error'],'height')
            width , order['error'] = positiveValue(order.get(data.get('width',None),None),order['error'],'width')
            depth , order['error'] = positiveValue(order.get(data.get('depth',None),None),order['error'],'depth')
            orderType , order['error'] = orderTypeCheck(order.get(data.get('orderType',None),None),order['error'],'order_type')
            buffer , order['error'] = positiveValue(order.get(data.get('buffer',None),None),order['error'],'buffer')


            orders.append({
                'ID':ID,
                'address':order[data['address']],
                'latitude':order[data['lat']],
                'longitude':order[data['lon']],
                'buffer':buffer,
                'weight':weight,
                'depth':depth,
                'height':height,
                'width':width,
                'time_to':timeTo if timeTo else None,
                'time_from':timeFrom if timeFrom else None,
                'order_type':orderType,
                'error':json.dumps(order.get('error',None))
            })

        new_df = pd.DataFrame(orders)
        fileId = NanoID()
        new_df.to_csv(f'temp/{fileId}_orders.csv',index=False)
        request.session['csvfileId'] = fileId
        return redirect('excel:addDeliveries')
    file = ExcelFile.objects.get(id= request.session['fileId'])
    err , df = read_file(file)
    df = df[list(df.columns)].fillna('None')
    return render(request, 'excelImport/fieldMapping.html',{'columns':df.columns , 'data':df.head(5).to_dict(orient='records')})
    

def addDeliveries(request):

    df = pd.read_csv(f'temp/{request.session["csvfileId"]}_orders.csv')
    if request.method == 'POST': 
        df['error'] = df['error'].apply(json.loads)
        df['errorLen'] = df['error'].apply(len)
        if not df.loc[df['errorLen'] > 0,'error'].empty:
            return render(request, 'excelImport/deliveries.html',{'data':pd.read_csv(f'temp/{request.session["csvfileId"]}_orders.csv').to_json(orient='records'), 'error':'There are still some invalid fields please correct them'})

        df['time_from'] = df['time_from'].apply(lambda x: parser.parse(x).replace(tzinfo=pytz.utc).timestamp() if not pd.isnull(x) else 0)
        df['time_to'] = df['time_to'].apply(lambda x: parser.parse(x).replace(tzinfo=pytz.utc).timestamp() if not pd.isnull(x) else 0)
        df['order_type'] = df['order_type'].apply(orderTypeconverter)
        df = df[['time_from','time_to','address','latitude','longitude','buffer','weight','depth','height','width','order_type']]
        for _ , order in df.iterrows():
            order = Order.objects.create(user=request.user,**order)
        
        cleanFolder('temp/')
        return redirect('delivery:deliveries')

    return render(request, 'excelImport/deliveries.html',{'data':df.to_json(orient='records')})

def correctData(request):
    if request.method == 'POST':
        df = pd.read_csv(f'temp/{request.session["csvfileId"]}_orders.csv')
        value = request.POST.get('value',None)
        changed = request.POST.get('field',None)
        id = request.POST.get('id',None)
        error = json.loads(df.loc[df['ID'] == int(id),'error'].iloc[0])
        if changed == 'address':
            add = geocoder(value)
            if add:
                lat = add.latitude
                lon = add.longitude
                df.loc[df['ID'] == int(id) , 'latitude'] = lat
                df.loc[df['ID'] == int(id) , 'longitude'] = lon
                if 'address' in error:
                    del error['address']
            else:
                error['address'] =  "Address could not be geocoded"
                df.loc[df['ID'] == int(id) , 'latitude'] = 0
                df.loc[df['ID'] == int(id) , 'longitude'] = 0

        elif changed == 'time_to':
            value , error = timeCorrection(value , error , 'time_to')
            df.loc[df['ID'] == int(id) , 'timeTo'] = value

        elif changed == 'time_from':
            value , error = timeCorrection(value,error, 'time_from')
            df.loc[df['ID'] == int(id) , 'timeFrom'] = value
        
        elif changed == 'order_type':
            value , error = orderTypeCheck(value,error,changed)
            df.loc[df['ID'] == int(id) , 'order_type'] = value
        
        else:
            value , error = positiveValue(value,error,changed)
            df.loc[df['ID'] == int(id) , changed] = value               


        df.loc[df['ID'] == int(id) , changed] = value
        df.loc[df['ID'] == int(id),'error'] = json.dumps(error)
        
        df.to_csv(f'temp/{request.session["csvfileId"]}_orders.csv',index=False)
        return JsonResponse(df.loc[df['ID'] == int(id) , :].to_json(orient='records'),status=200 , safe=False)


def download_example(request):
    file_path = os.path.join(settings.BASE_DIR, 'Demo Deliveries.xlsx')
    if os.path.exists(file_path):
        with open(file_path, 'rb') as fh:
            response = HttpResponse(fh.read(), content_type="application/vnd.ms-excel")
            response['Content-Disposition'] = 'inline; filename=' + os.path.basename(file_path)
            return response
    raise Http404

templates/excelImport/deliveries.html
{% extends 'bases/base.html' %}
{% load static %}

{% block title %} Excel Import {% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ag-grid/Docs-27.2.1-20220420/styles/ag-grid.min.css" integrity="sha512-2euLJS00YpxIOHKIinN1Nb+MtmeMLxiDYMz7R0no2bt1/BzdMXaNHByElWmLkqrWMrjOt9oNEFzoyHSzRJiIWw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
{% endblock %}

{% block scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/ag-grid/Docs-27.2.1-20220420/ag-grid-community.min.js" integrity="sha512-qx1v32Xx2Pd/tkbz70aorurAF6/214hjy+otgy+GhoLWMnVt02lwmRSGMtdqYb6TuqtRppD9LoQySFWvZjHoFw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
{% endblock %}

{% block css %}
<style>
    .demo-table{
        max-width: 100%;
        max-height: calc(100vh - 300px);
    }
    .table{
        border-collapse: separate; /* Don't collapse */
        border-spacing: 0;
    }
    .table th{
        min-width: 100px;
    }
    .table thead{
        position:sticky;
        top: 0 ;
        background: white;
        height:50px;
    }
    .ag-theme-alpine{
        font-family: 'poppins';
    }
    .ag-theme-alpine input[class^=ag-][type=text]{
        color: black !important;
    }
    .tooltip-inner{
        min-width: 250px;
    }
    .tooltip .bs-tooltip-bottom , .tooltip-inner {
        background-color: white !important;
        border-color: white !important;
        color: #000 !important;
    }
    .bs-tooltip-bottom .tooltip-arrow::before {
        border-bottom-color: #fff;
    }




</style>
{% endblock %}

{% block body %}
<div class="container d-flex justify-content-center align-items-center h100-70 flex-column">
    <h3 class="text-syn mb-4">orders Import</h3>
    <div id="myGrid" style="height: calc(100vh - 300px); width:100%;" class="ag-theme-alpine"></div>
    <div>
        <a href="{% url 'excel:fieldMapping' %}"><button class="btn btn-secondary mt-3" > Back </button></a>
        <button class="btn btn-primary mt-3" form="import" > import </button>
        <form action="{% url 'excel:addDeliveries' %}" method="post" id="import" hidden>
            {% csrf_token %}
        </form>
    </div>

</div>
{% endblock %}

{% block js %}
<script >

    window.CSRF_TOKEN='{{ csrf_token }}';

    class DatePicker {
    // gets called once before the renderer is used
        init(params) {
            // create the cell
            this.eInput = document.createElement('input');
            this.eInput.value = params.value;
            this.eInput.classList.add('ag-input');
            this.eInput.style.height = '100%';

            // https://jqueryui.com/datepicker/
            $(this.eInput).datepicker({
            dateFormat: 'dd/mm/yy',
            onSelect: () => {
                this.eInput.focus();
            },
            });
        }

        // gets called once when grid ready to insert the element
        getGui() {
            return this.eInput;
        }

        // focus and select can be done after the gui is attached
        afterGuiAttached() {
            this.eInput.focus();
            this.eInput.select();
        }

        // returns the new value after editing
        getValue() {
            return this.eInput.value;
        }

        // any cleanup we need to be done here
        destroy() {
            // but this example is simple, no cleanup, we could
            // even leave this method out as it's optional
        }

        // if true, then this editor will appear in a popup
        isPopup() {
            // and we could leave this method out also, false is the default
            return false;
        }
    }

    const postiveValue = (params)=>{
        error = JSON.parse(params.node.data.error)
        if(params.colDef.field in error){
            return ['bg-danger text-white']
        }
        else{
            return []
        }
    }

    var gridOptions = {
    columnDefs: [
        { headerName: '', field: 'error' , width: 100,wrapText: true,autoHeight: true,editable: false,cellClass:"",
            headerCheckboxSelection: true,
            headerCheckboxSelectionFilteredOnly: true,
            checkboxSelection: true,
            cellRenderer: (params)=>{
                error = JSON.parse(params.node.data.error)
                if(Object.keys(error).length <= 0){
                    return '<h6 class="w-100 text-center my-auto text-success" ><i class="fas fa-check-circle"></i></h6>';
                }

                errorText = ``
                for(let key in error){
                    errorText += `<p class="m-0 text-nowrap" style="font-size:11px!important;"> ${error[key]} </p>`
                }
                return `<h6 class="w-100 text-center my-auto text-danger" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-html="true" tabindex="0" title='${errorText}'><i class="fas fa-exclamation-circle"></i></h6>`;
            },
        },
        { headerName: 'Address', field: 'address' ,minWidth: 300,wrapText: true,autoHeight: true ,cellClass: function(params) {
            error = JSON.parse(params.node.data.error)
            if('address' in error){
                return ['bg-danger text-white']
            }
            else{
                return []
            }
        },
        },
        { headerName: 'Latitude', field: 'latitude', },
        { headerName: 'Longitude', field: 'longitude' ,},
        { headerName: 'Time From', field: 'time_from' ,cellClass: function(params) {
            error = JSON.parse(params.node.data.error)
            if('time_from' in error){
                return ['bg-danger text-white']
            }
            else{
                return []
            }
        },
        },
        { headerName: 'Time To', field: 'time_to' ,cellClass: function(params) {
            error = JSON.parse(params.node.data.error)
            if('time_to' in error){
                return ['bg-danger text-white']
            }
            else{
                return []
            }
        },
        },
        { headerName: 'Buffer', field: 'buffer' , width: 100,cellClass: postiveValue,},
        { headerName: 'Height', field: 'height' , width: 100,cellClass: postiveValue,},
        { headerName: 'Width', field: 'width' , width: 100,cellClass: postiveValue,},
        { headerName: 'Depth', field: 'depth' , width: 100,cellClass: postiveValue,},
        { headerName: 'Weight', field: 'weight' , width: 100,cellClass: postiveValue,},
        { headerName: 'Order Type', field: 'order_type' , width: 150,cellClass: postiveValue,
        }
    ],
    defaultColDef: {
        editable: params => {
            return params.node.data.error !== '{}'
        }
    },
    onViewportChanged: function(){
        
        var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))

        var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
        tooltip =  new bootstrap.Tooltip(tooltipTriggerEl)
        return tooltip
        })
        
    },
    suppressRowClickSelection: true,
    rowSelection: 'multiple',
    getRowId: (params) => {
        return params.data.ID;
    },
    onCellValueChanged: function(data) {
        $.ajax({
            url: "{% url 'excel:update' %}",
            type: "POST",
            data: {
                id: data.data.ID,
                field: data.colDef.field,
                value: data.newValue,
                'csrfmiddlewaretoken': window.CSRF_TOKEN
            },
            success: function(res) {
                res = JSON.parse(res)
                data.node.setData(res[0])
            }
        })
    },
    rowData: {{ data | safe }}
    }
    document.addEventListener('DOMContentLoaded', () => {
        var eGridDiv = document.querySelector('#myGrid');
        new agGrid.Grid(eGridDiv, gridOptions);
    }); 
   
    
    
</script>
{% endblock %}

templates/excelImport/fieldMapping.html
{% extends 'bases/base.html' %}
{% load static %}

{% block title %} Excel Import {% endblock %}

{% block stylesheets %}
{% endblock %}

{% block scripts %}
{% endblock %}

{% block css %}
<style>
    .demo-table{
        max-width: 100%;
    }
    th{
        min-width: 200px;
    }
    table thead{
        position:sticky;
        top: 0 ;
        background: white;
        height:50px;
    }

    
</style>
{% endblock %}

{% block body %}

<div class="container d-flex justify-content-center align-items-center h100-70 flex-column">
    <h3 class="text-syn mb-4">Define order fields</h3>
    <div class="w-100 d-flex justify-content-end align-items-center flex-nowrap mb-2">
        <label for="" class="me-2"> Geocode provided </label>
        <input type="checkbox" name="geocoded1" checked>
    </div>
    <div class="table-responsive demo-table w-100 rounded border">
        <form action="{% url 'excel:fieldMapping' %}" id="columns" method="POST">
           
            {% csrf_token %}
            <input type="checkbox" hidden name="geocoded" value="True" checked>
            <table class="table table-striped">
                <thead class="shadow">
                    <tr>
                        {% for col in columns %}
                        <th scope="col"><select name="{{col}}" id="" class="form-select w-100" style="min-width: 200px;" >
                            <option value="none"></option>
                            <option value="address">Address</option>
                            <option value="lat">Latitude</option>
                            <option value="lon">longitude</option>
                            <option value="timeFrom">Time from</option>
                            <option value="timeTo">Time to</option>
                            <option value="buffer">Buffer</option>
                            <option value="height">Height</option>
                            <option value="width">Width</option>
                            <option value="depth">Depth</option>
                            <option value="weight">Weight</option>
                            <option value="orderType">Order type</option>
                        </select></th>
                        {% endfor %}
                    </tr>
                    <tr>
                        {% for col in columns %}
                        <th scope="col"> <h6 class="fw-bold">{{col}}</h6> </th>
                        {% endfor %}
                    </tr>
                </thead>
                <tbody>
                    {% for d in data %}
                    <tr>
                        {% for key,value in d.items %}
                        <td > <p style="font-size: 14px;">{{value}}</p></td>
                        {% endfor %}
                    </tr>
                    {% endfor %}
                </tbody>
    
            </table>
        </form>
    </div>

    <div>
        <a href="{% url 'excel:import' %}"><button class="btn btn-secondary mt-3" > Back </button></a>
        <button class="btn btn-primary mt-3" form="columns" > Next </button>
    </div>

</div>


{% endblock %}

{% block js %}
<script>

    const noSameValue = (event) => {
        
        document.querySelectorAll('select').forEach((e)=>{
            if (e.getAttribute('name') != this.getAttribute('name')){
                if (e.value === this.value){
                    e.value = 'none'
                }
            }
        })
    }

    const checkLatLon = ()=>{
        valid = true
        let lat = false
        let lon = false
        if (document.querySelector('[name="geocoded1"]').checked){
            document.querySelectorAll('select').forEach((e)=>{
                if (e.value === 'lat'){
                    lat = true
                }
                if (e.value === 'lon'){
                    lon = true
                }

            })

            if (!lat || !lon){
                valid = false
            }


        }

        return valid
        
    }

    const checkAddressField = ()=>{
        let valid = false
       
        document.querySelectorAll('select').forEach((e)=>{
            if (e.value === 'address'){
                valid = true
            }
            

        })
        return valid

    }

    document.querySelectorAll('select').forEach((e)=>{
        e.addEventListener('change',noSameValue)
    })


    document.querySelector('[name="geocoded1"]').addEventListener('change',function (event){
        document.querySelector('[name="geocoded"]').checked = this.checked
        })

    document.getElementById('columns').addEventListener('submit',function (event){
        event.preventDefault()
        if (checkAddressField()){

            if(checkLatLon()){
                this.submit()
            }
            else{
                alert("please provide latitude and longitude") 
            }
        }
        else{
            alert("please provide a address line")
        }
    })



</script>
{% endblock %}

templates/excelImport/importExcel.html
{% extends 'bases/base.html' %}
{% load static %}

{% block title %} Excel Import {% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="https://unpkg.com/dropzone@5/dist/min/dropzone.min.css" type="text/css" />
{% endblock %}

{% block scripts %}
<script src="https://unpkg.com/dropzone@5/dist/min/dropzone.min.js"></script>
{% endblock %}


{% block css %}
<style>
    .dropzoneDiv{
        min-width:250px;
        height:100%;
        width:100%;
        max-width: 500px;
        min-height:150px;
        max-height:350px;
        cursor:pointer;
        border: 2px dashed #126caa;
    }
</style>
{% endblock %}

{% block body %}
<div class="container d-flex h100-70 justify-content-center align-items-center flex-column">
    <h2 class="text-center text-syn mb-4" >
        Excel Import
    </h2>
    <form action="{% url 'excel:import'%}" method="post"
      class="dropzone dropzoneDiv rounded"
      id="my-dropzone">
      {% csrf_token %}
      <div class="dz-default dz-message"><h4  class="text-grey"> Drop here to upload </h4></div>
    </form>

    <a href="{% url 'excel:download_example' %}" class="link mt-3 link-grey" download>
        Download .xlsx template file
    </a>

    <button class="btn btn-primary mt-3" onclick="submitform()" > Next </button>
    
</div>
{% endblock %}

{% block js %}
<script>


    let myDropzone;
    Dropzone.options.myDropzone = {
        maxFiles : 1,
        acceptedFiles:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel , .csv',
        autoProcessQueue:false,
        addRemoveLinks:true,
        init: function() {
               myDropzone = this;
               this.on('success',(file, response)=>{
                 window.location.href = "{% url 'excel:fieldMapping' %}"
               })
        }
    }

    const submitform = ()=>{
        myDropzone.processQueue()
    }


   

    
    

</script>
{% endblock %}